---
# handlers file for podman-app
- name: Reload SystemD and restart application service
  ansible.builtin.systemd:
    service: "{{ podman_app_service_name }}"
    state: restarted
    daemon_reload: true
